// Style Dictionary formatter — generates internal/design/tokens.go
// Do not edit the output file directly; edit design/tokens.json instead.

export function format({ dictionary }) {
  const colors = dictionary.allTokens.filter(t => t.path[0] === 'nexus' && t.path[1] === 'color');
  const grid   = dictionary.allTokens.filter(t => t.path[0] === 'nexus' && t.path[1] === 'grid');
  const type   = dictionary.allTokens.filter(t => t.path[0] === 'nexus' && t.path[1] === 'type');

  // nexus.color.screenBg → ScreenBg  (drop 'nexus' + group, PascalCase remainder)
  const constName = t => t.path.slice(2).map(p => p.charAt(0).toUpperCase() + p.slice(1)).join('');

  const desc = t => t.$description || '';

  const colorConst = t => {
    const hex = (t.$value || '').replace('#', '');
    const r = hex.slice(0,2), g = hex.slice(2,4), b = hex.slice(4,6);
    return `\t${constName(t)} = color.RGBA{R: 0x${r}, G: 0x${g}, B: 0x${b}, A: 0xff} // ${desc(t)}`;
  };

  const numConst = t => {
    const v = t.$value;
    return `\t${constName(t)} = ${v} // ${desc(t)}`;
  };

  return `// Code generated by design/sd.config.js — DO NOT EDIT.
// Source: design/tokens.json
// Regenerate: cd design && npm run build

package design

import "image/color"

// Hardware display color tokens.
// These are the only values permitted in zone/renderer.go and all plugins.
// Plugins never choose colors — the host maps Severity → color using this table.
var (
${colors.map(colorConst).join('\n')}
)

// Hardware display grid constants (pixels, native 640×48 coordinate space).
const (
${grid.map(numConst).join('\n')}
)

// Hardware display type scale (font sizes in pixels).
const (
${type.map(numConst).join('\n')}
)
`;
}
