// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: layout.sql

package db

import (
	"context"
	"database/sql"
)

const countPages = `-- name: CountPages :one
SELECT COUNT(*) FROM pages
`

func (q *Queries) CountPages(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countPages)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteAllPages = `-- name: DeleteAllPages :exec
DELETE FROM pages
`

func (q *Queries) DeleteAllPages(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteAllPages)
	return err
}

const deletePage = `-- name: DeletePage :exec
DELETE FROM pages WHERE id = ?
`

func (q *Queries) DeletePage(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deletePage, id)
	return err
}

const deleteZone = `-- name: DeleteZone :exec
DELETE FROM zones WHERE id = ?
`

func (q *Queries) DeleteZone(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteZone, id)
	return err
}

const getZoneConfigJSON = `-- name: GetZoneConfigJSON :one
SELECT config_json FROM zones WHERE id = ?
`

func (q *Queries) GetZoneConfigJSON(ctx context.Context, id string) (string, error) {
	row := q.db.QueryRowContext(ctx, getZoneConfigJSON, id)
	var config_json string
	err := row.Scan(&config_json)
	return config_json, err
}

const getZonePageID = `-- name: GetZonePageID :one
SELECT page_id FROM zones WHERE id = ?
`

func (q *Queries) GetZonePageID(ctx context.Context, id string) (int64, error) {
	row := q.db.QueryRowContext(ctx, getZonePageID, id)
	var page_id int64
	err := row.Scan(&page_id)
	return page_id, err
}

const insertPage = `-- name: InsertPage :execlastid
INSERT INTO pages(name, ord) VALUES(?, ?)
`

type InsertPageParams struct {
	Name string
	Ord  int64
}

func (q *Queries) InsertPage(ctx context.Context, arg InsertPageParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, insertPage, arg.Name, arg.Ord)
	if err != nil {
		return 0, err
	}
	return result.LastInsertId()
}

const insertPageWithID = `-- name: InsertPageWithID :exec
INSERT INTO pages(id, name, ord) VALUES(?, ?, ?)
`

type InsertPageWithIDParams struct {
	ID   int64
	Name string
	Ord  int64
}

func (q *Queries) InsertPageWithID(ctx context.Context, arg InsertPageWithIDParams) error {
	_, err := q.db.ExecContext(ctx, insertPageWithID, arg.ID, arg.Name, arg.Ord)
	return err
}

const insertZone = `-- name: InsertZone :exec
INSERT INTO zones(id, page_id, ord, width_px, plugin, refresh_ms, align,
                  on_tap, choices_json, config_json, theme_json)
VALUES(?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertZoneParams struct {
	ID          string
	PageID      int64
	Ord         int64
	WidthPx     int64
	Plugin      string
	RefreshMs   int64
	Align       string
	OnTap       string
	ChoicesJson string
	ConfigJson  string
	ThemeJson   string
}

func (q *Queries) InsertZone(ctx context.Context, arg InsertZoneParams) error {
	_, err := q.db.ExecContext(ctx, insertZone,
		arg.ID,
		arg.PageID,
		arg.Ord,
		arg.WidthPx,
		arg.Plugin,
		arg.RefreshMs,
		arg.Align,
		arg.OnTap,
		arg.ChoicesJson,
		arg.ConfigJson,
		arg.ThemeJson,
	)
	return err
}

const listPages = `-- name: ListPages :many
SELECT id, name, ord FROM pages ORDER BY ord
`

func (q *Queries) ListPages(ctx context.Context) ([]Page, error) {
	rows, err := q.db.QueryContext(ctx, listPages)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Page
	for rows.Next() {
		var i Page
		if err := rows.Scan(&i.ID, &i.Name, &i.Ord); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listZonesForPage = `-- name: ListZonesForPage :many
SELECT id, page_id, ord, width_px, plugin, refresh_ms, align,
       on_tap, choices_json, config_json, theme_json
FROM zones
WHERE page_id = ?
ORDER BY ord
`

type ListZonesForPageRow struct {
	ID          string
	PageID      int64
	Ord         int64
	WidthPx     int64
	Plugin      string
	RefreshMs   int64
	Align       string
	OnTap       string
	ChoicesJson string
	ConfigJson  string
	ThemeJson   string
}

func (q *Queries) ListZonesForPage(ctx context.Context, pageID int64) ([]ListZonesForPageRow, error) {
	rows, err := q.db.QueryContext(ctx, listZonesForPage, pageID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListZonesForPageRow
	for rows.Next() {
		var i ListZonesForPageRow
		if err := rows.Scan(
			&i.ID,
			&i.PageID,
			&i.Ord,
			&i.WidthPx,
			&i.Plugin,
			&i.RefreshMs,
			&i.Align,
			&i.OnTap,
			&i.ChoicesJson,
			&i.ConfigJson,
			&i.ThemeJson,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePage = `-- name: UpdatePage :exec
UPDATE pages SET name = ?, ord = ? WHERE id = ?
`

type UpdatePageParams struct {
	Name string
	Ord  int64
	ID   int64
}

func (q *Queries) UpdatePage(ctx context.Context, arg UpdatePageParams) error {
	_, err := q.db.ExecContext(ctx, updatePage, arg.Name, arg.Ord, arg.ID)
	return err
}

const updatePageOrd = `-- name: UpdatePageOrd :exec
UPDATE pages SET ord = ? WHERE id = ?
`

type UpdatePageOrdParams struct {
	Ord int64
	ID  int64
}

func (q *Queries) UpdatePageOrd(ctx context.Context, arg UpdatePageOrdParams) error {
	_, err := q.db.ExecContext(ctx, updatePageOrd, arg.Ord, arg.ID)
	return err
}

const updateZone = `-- name: UpdateZone :execresult
UPDATE zones
SET page_id = ?, ord = ?, width_px = ?, plugin = ?, refresh_ms = ?, align = ?,
    on_tap = ?, choices_json = ?, config_json = ?, theme_json = ?
WHERE id = ?
`

type UpdateZoneParams struct {
	PageID      int64
	Ord         int64
	WidthPx     int64
	Plugin      string
	RefreshMs   int64
	Align       string
	OnTap       string
	ChoicesJson string
	ConfigJson  string
	ThemeJson   string
	ID          string
}

func (q *Queries) UpdateZone(ctx context.Context, arg UpdateZoneParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, updateZone,
		arg.PageID,
		arg.Ord,
		arg.WidthPx,
		arg.Plugin,
		arg.RefreshMs,
		arg.Align,
		arg.OnTap,
		arg.ChoicesJson,
		arg.ConfigJson,
		arg.ThemeJson,
		arg.ID,
	)
}

const updateZoneConfigJSON = `-- name: UpdateZoneConfigJSON :exec
UPDATE zones SET config_json = ? WHERE id = ?
`

type UpdateZoneConfigJSONParams struct {
	ConfigJson string
	ID         string
}

func (q *Queries) UpdateZoneConfigJSON(ctx context.Context, arg UpdateZoneConfigJSONParams) error {
	_, err := q.db.ExecContext(ctx, updateZoneConfigJSON, arg.ConfigJson, arg.ID)
	return err
}

const updateZoneOrd = `-- name: UpdateZoneOrd :exec
UPDATE zones SET ord = ? WHERE id = ? AND page_id = ?
`

type UpdateZoneOrdParams struct {
	Ord    int64
	ID     string
	PageID int64
}

func (q *Queries) UpdateZoneOrd(ctx context.Context, arg UpdateZoneOrdParams) error {
	_, err := q.db.ExecContext(ctx, updateZoneOrd, arg.Ord, arg.ID, arg.PageID)
	return err
}

const updateZonePlugin = `-- name: UpdateZonePlugin :exec
UPDATE zones SET plugin = ? WHERE id = ?
`

type UpdateZonePluginParams struct {
	Plugin string
	ID     string
}

func (q *Queries) UpdateZonePlugin(ctx context.Context, arg UpdateZonePluginParams) error {
	_, err := q.db.ExecContext(ctx, updateZonePlugin, arg.Plugin, arg.ID)
	return err
}
