// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

type Page struct {
	ID   int64
	Name string
	Ord  int64
}

type PayloadCache struct {
	ZoneID    string
	PluginID  string
	Payload   string
	FetchedAt int64
}

type SchemaVersion struct {
	Version int64
}

type Setting struct {
	Key   string
	Value string
}

type Zone struct {
	ID          string
	PageID      int64
	Ord         int64
	WidthPx     int64
	Plugin      string
	RefreshMs   int64
	Align       string
	ConfigJson  string
	ThemeJson   string
	OnTap       string
	ChoicesJson string
}
