// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: payload_cache.sql

package db

import (
	"context"
)

const deletePayloadCache = `-- name: DeletePayloadCache :exec
DELETE FROM payload_cache WHERE zone_id = ?
`

func (q *Queries) DeletePayloadCache(ctx context.Context, zoneID string) error {
	_, err := q.db.ExecContext(ctx, deletePayloadCache, zoneID)
	return err
}

const getPayloadCache = `-- name: GetPayloadCache :one
SELECT plugin_id, payload, fetched_at FROM payload_cache WHERE zone_id = ?
`

type GetPayloadCacheRow struct {
	PluginID  string
	Payload   string
	FetchedAt int64
}

func (q *Queries) GetPayloadCache(ctx context.Context, zoneID string) (GetPayloadCacheRow, error) {
	row := q.db.QueryRowContext(ctx, getPayloadCache, zoneID)
	var i GetPayloadCacheRow
	err := row.Scan(&i.PluginID, &i.Payload, &i.FetchedAt)
	return i, err
}

const upsertPayloadCache = `-- name: UpsertPayloadCache :exec
INSERT INTO payload_cache(zone_id, plugin_id, payload, fetched_at)
VALUES(?, ?, ?, ?)
ON CONFLICT(zone_id) DO UPDATE SET
    plugin_id  = excluded.plugin_id,
    payload    = excluded.payload,
    fetched_at = excluded.fetched_at
`

type UpsertPayloadCacheParams struct {
	ZoneID    string
	PluginID  string
	Payload   string
	FetchedAt int64
}

func (q *Queries) UpsertPayloadCache(ctx context.Context, arg UpsertPayloadCacheParams) error {
	_, err := q.db.ExecContext(ctx, upsertPayloadCache,
		arg.ZoneID,
		arg.PluginID,
		arg.Payload,
		arg.FetchedAt,
	)
	return err
}
