// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"
	"database/sql"
)

type Querier interface {
	CountPages(ctx context.Context) (int64, error)
	DeleteAllPages(ctx context.Context) error
	DeletePage(ctx context.Context, id int64) error
	DeletePayloadCache(ctx context.Context, zoneID string) error
	DeleteZone(ctx context.Context, id string) error
	GetAllSettings(ctx context.Context) ([]Setting, error)
	GetPayloadCache(ctx context.Context, zoneID string) (GetPayloadCacheRow, error)
	GetSetting(ctx context.Context, key string) (string, error)
	GetZoneConfigJSON(ctx context.Context, id string) (string, error)
	GetZonePageID(ctx context.Context, id string) (int64, error)
	InsertPage(ctx context.Context, arg InsertPageParams) (int64, error)
	InsertPageWithID(ctx context.Context, arg InsertPageWithIDParams) error
	InsertZone(ctx context.Context, arg InsertZoneParams) error
	ListPages(ctx context.Context) ([]Page, error)
	ListZonesForPage(ctx context.Context, pageID int64) ([]ListZonesForPageRow, error)
	UpdatePage(ctx context.Context, arg UpdatePageParams) error
	UpdatePageOrd(ctx context.Context, arg UpdatePageOrdParams) error
	UpdateZone(ctx context.Context, arg UpdateZoneParams) (sql.Result, error)
	UpdateZoneConfigJSON(ctx context.Context, arg UpdateZoneConfigJSONParams) error
	UpdateZoneOrd(ctx context.Context, arg UpdateZoneOrdParams) error
	UpdateZonePlugin(ctx context.Context, arg UpdateZonePluginParams) error
	UpsertPayloadCache(ctx context.Context, arg UpsertPayloadCacheParams) error
	UpsertSetting(ctx context.Context, arg UpsertSettingParams) error
}

var _ Querier = (*Queries)(nil)
