// Code generated by design/sd.config.js — DO NOT EDIT.
// Source: design/tokens.json
// Regenerate: cd design && npm run build

package design

import "image/color"

// Hardware display color tokens.
// These are the only values permitted in zone/renderer.go and all plugins.
// Plugins never choose colors — the host maps Severity → color using this table.
var (
	ScreenBg = color.RGBA{R: 0x05, G: 0x05, B: 0x05, A: 0xff} // Panel background
	Bezel = color.RGBA{R: 0x17, G: 0x17, B: 0x17, A: 0xff} // Device frame (host UI only)
	Divider = color.RGBA{R: 0x22, G: 0x22, B: 0x22, A: 0xff} // Slot separator lines
	TouchDot = color.RGBA{R: 0x3a, G: 0x3a, B: 0x3a, A: 0xff} // Expandable zone affordance dot
	Label = color.RGBA{R: 0xb8, G: 0xb8, B: 0xb8, A: 0xff} // Zone label text
	Value = color.RGBA{R: 0xec, G: 0xec, B: 0xec, A: 0xff} // Neutral readout text
	Unit = color.RGBA{R: 0x8a, G: 0x8a, B: 0x8a, A: 0xff} // Demoted units (°C, %, rpm)
	Info = color.RGBA{R: 0x5a, G: 0xa0, B: 0xe0, A: 0xff} // Trend lines, neutral accents — always neutral, never state
	InfoArea = color.RGBA{R: 0x16, G: 0x34, B: 0x4a, A: 0xff} // Area fill under info trend line
	Ok = color.RGBA{R: 0x79, G: 0xc2, B: 0x67, A: 0xff} // Healthy state — text and markers
	OkBar = color.RGBA{R: 0x4f, G: 0x8a, B: 0x3a, A: 0xff} // Healthy bar fill
	Warn = color.RGBA{R: 0xf0, G: 0xa8, B: 0x30, A: 0xff} // Warning state
	WarnDim = color.RGBA{R: 0xb0, G: 0x7a, B: 0x1e, A: 0xff} // Warning unit and secondary text
	Crit = color.RGBA{R: 0xe2, G: 0x62, B: 0x5f, A: 0xff} // Critical / failure state
	CritDim = color.RGBA{R: 0x6a, G: 0x2f, B: 0x2f, A: 0xff} // Critical threshold line fill
)

// Hardware display grid constants (pixels, native 640×48 coordinate space).
const (
	DisplayWidth = 640 // Hardware display width in pixels
	DisplayHeight = 48 // Hardware display height in pixels
	SlotCount = 6 // Number of slots across the display
	SlotWidth = 100 // Width of a single slot in pixels
	SlotGap = 8 // Gap between slots in pixels
	ContentPadLeft = 8 // Left padding inside each slot
	LabelBaselineY = 15 // Label text baseline (y coordinate)
	ValueBaselineY = 38 // Value text baseline (y coordinate)
	DividerY1 = 9 // Slot divider top y
	DividerY2 = 39 // Slot divider bottom y
	TouchDotX = 92 // Touch affordance dot x (slot-local)
	TouchDotY = 42 // Touch affordance dot y
	TouchDotRadius = 1.4 // Touch affordance dot radius
	GrabHandleX = 308 // Detail overlay grab handle x
	GrabHandleY = 2.5 // Detail overlay grab handle y
	GrabHandleW = 24 // Detail overlay grab handle width
	GrabHandleH = 2.5 // Detail overlay grab handle height
)

// Hardware display type scale (font sizes in pixels).
const (
	SizeLabel = 10 // Zone label font size
	SizeValue = 22 // Zone value font size
	SizeValueDetail = 26 // Detail view value font size
	SizeUnit = 13 // Unit text font size
	SizeCaption = 9 // Caption / sub-value font size
)
