// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function DeleteImage(arg1:string):Promise<void>;

export function GetConfig():Promise<main.Config>;

export function GetImagePreview(arg1:string):Promise<string>;

export function UpdateConfig(arg1:main.Config):Promise<void>;

export function UploadImage(arg1:string,arg2:Array<number>):Promise<main.ImageInfo>;
