// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeleteImage(arg1) {
  return window['go']['main']['App']['DeleteImage'](arg1);
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetImagePreview(arg1) {
  return window['go']['main']['App']['GetImagePreview'](arg1);
}

export function UpdateConfig(arg1) {
  return window['go']['main']['App']['UpdateConfig'](arg1);
}

export function UploadImage(arg1, arg2) {
  return window['go']['main']['App']['UploadImage'](arg1, arg2);
}
